# -*- coding: utf-8 -*-
"""Clase_8_8 septiembre.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1issKEMdrjpMbHwFlgAfZHE1_TMLqA6RX

<center>

#**Colegio Siglo XXI - El Socorro**
#**Presentado por: Sara Valentina Forero Gutiérrez**
#**Grado: Décimo**
#**8 de Septiembre**

#**¿Qué es python?**
# Python es un lenguaje de programación multiplataforma y de código abierto que puede utilizarse tanto para desarrollo web, creación de software y procesamiento de datos, entre muchos otros propósitos. Esta versatilidad y facilidad para aprenderlo (es ampliamente considerado el lenguaje más sencillo de aprender) lo han convertido en el lenguaje de programación más popular del mundo, según el índice PYPL.
#Fecha de lanzamiento: Python empieza con Guido Van Rossum empezando su desarrollo en 1989 y empezando a implementarlo en febrero de 1991, momento en el que se publicó la primera versión pública: la 0.9.0.
# Creadores: Guido Van Rossum es el creador y responsable de que Python exista. 

# Recuperado de: https://platzi.com/blog/python/?utm_source=google&utm_medium=cpc&utm_campaign=17739691128&utm_adgroup=&utm_content=&gclid=Cj0KCQjwpeaYBhDXARIsAEzItbFnuQcnDlC2HVLu2bSBP7sL53Vx0SzPogPWCDpd0biLPQIQOmb1IdAaAk7DEALw_wcB&gclsrc=aw.ds / https://www.tokioschool.com/noticias/historia-python/
"""

print("Esto es una suma")
numero_uno = 6
numero_dos = 7 
resultado = numero_uno + numero_dos
print(resultado)

print("Esto es una resta")
numero_uno = 23
numero_dos = 10
resultado = numero_uno - numero_dos
print(resultado)

print("Esto es una multiplicacion")
numero_uno = 7
numero_dos = 7 
resultado = numero_uno * numero_dos
print(resultado)

print("Esto es una division")
numero_uno = 100
numero_dos = 20
resultado = numero_uno / numero_dos
print(resultado)

"""# Ejercicios de tipos de Datos simples

#Ejercicio 1 

Escribir un programa que pregunte el nombre del usuario en la consola y un número entero e imprima por pantalla en líneas distintas el nombre del usuario tantas veces como el número introducido
"""

nombre = input("¿Cómo te llamas?")
n=input("Introduce un número entero:")
print((nombre + "\n") * int(n))

"""#Ejercicio 2

Escribir un programa que pida al usuario su peso (en Kg) y estatura (en metros) , calcule el indice en masa corporal y lo almacene en una variable, e imprima
por pantalla la frase 'Tu indice de masa corporal es < imc >' donde '< imc >' es el índice de masa corporal calculando redondeando con dos decimales. 
"""

peso = input("¿Cuál es tu peso en kg?")
estatura = input("¿Cuál es tu estatura en metros?")
imc = round(float(peso)/float(estatura)**2,2)
print("Tu índice de masa corporal es " + str(imc))

"""#**LIBRERÍAS EN PYTHON**  
A grandes rasgos, cabe destacar que en programación una librería responde al conjunto de funcionalidades que permiten al usuario  llevar a cabo nuevas tareas que antes no se podían realizar.

Es decir, las librerías de Python responden al conjunto de implementaciones que permiten codificar este lenguaje, con el objeto de crear una interfaz independiente.
"""

